# ============================================
# LABSOC HOME - Kibana Configuration
# ============================================

# Server
server.name: labsoc-kibana
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "LabSocKibana2026!"

# Security
xpack.security.encryptionKey: "labsoc-encryption-key-32-chars!!"
xpack.encryptedSavedObjects.encryptionKey: "labsoc-encryption-key-32-chars!!"
xpack.reporting.encryptionKey: "labsoc-encryption-key-32-chars!!"

# Logging
logging.root.level: info

# Telemetry
telemetry.enabled: false
telemetry.optIn: false
